version: '3'
services:
  minimal-redis:
    image: redis:alpine
    container_name: minimal-redis
    ports:
      - "6379:6379"

  minimal-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: minimal-mongodb
    ports:
      - "27017:27017"

  # python-interaction:
  #   build:
  #     context: .
  #   depends_on:
  #     - minimal-redis
  #     - minimal-mongodb
