version: '3'
services:
  minimal-redis:
    image: redis:alpine
    restart: always
    container_name: minimal-redis
    command: redis-server --save 20 1 --loglevel warning --logfile /dev/null
    ports:
      - "6379:6379"

  minimal-mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    container_name: minimal-mongodb
    ports:
      - "27017:27017"

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: always    
    container_name: minimal-timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
  
